# https://en.wikipedia.org/wiki/Glossary_of_climate_change
CLIMATE_CHANGE_RELATED_WORDS = [
    'adapt',
    'adaptation',
    'all-time',
    'arctic',
    'carbon',
    'celsius',
    'climate',
    # 'change',
    'crisis',
    'cooling',
    'degree',
    'dioxide',
    'drought',
    'ecosystem',
    'energy',
    'environmental',
    'environment',
    'eco',
    'effect',
    'extreme',
    'footprint',
    'fossil',
    'fuel',
    'gas',
    'glacial',
    'global',
    'greenhouse',
    'green',
    'greenland',
    'historic',
    'historical',
    'history',
    'hottest',
    'high',
    'ice',
    'life-threatening',
    'megadrought',
    'meteorologist',
    'meteorology',
    'methane',
    'mitigation',
    'natural',
    'nitrous',
    'ozone',
    'offset',
    'oxide',
    'planet',
    'policies',
    'policy',
    'pollution',
    'record',
    'record-breaking',
    'record-setting',
    'report',
    'reversable',
    'reverse',
    'renewable',
    'resource',
    'rise',
    'rising',
    'science',
    'scientist',
    'sea ice',
    'sea',
    'sea-level',
    'severe',
    'shrinkage',
    'solar',
    'temperature',
    'unprecedented',
    'warm',
    'warmest',
    'warmed',
    'warming',
    #'weather',
]
CLIMATE_CHANGE_RELATED_WORDS.sort()

CLIMATE_CHANGE_RELATED_PHRASES = [
    'arctic shrinkage',
    'carbon dioxide',
    'carbon footprint',
    'carbon offset',
    'carbon tax',
    'climate change',
    'climate crisis',
    'climate justice',
    'extreme weather event',
    'fossil fuel',
    'global climate',
    'global cooling',
    'global warming',
    'global warming controversy',
    'global warming denial',
    'greenhouse debt',
    'greenhouse effect',
    'greenhouse gas',
    'greenland ice sheet',
    'historical temperature record',
    'ice sheet',
    'nitrous oxide',
    'record setting'
    'record breaking',
    'record breaking',
    'renewable resource',
    'sea level',
]
CLIMATE_CHANGE_RELATED_PHRASES.sort()

if __name__ == '__main__':
    main()
