CC_WORDS = [
"anthropogenic",
"emission",
"emissions",
"heat-trapping",
"methane",
"coal",
"oil",
"gas",
"fracking",
"keystone",
"carbon",
"CO2",
"chlorofluorocarbon",
"chlorofluorocarbons",
"fluorocarbon",
"fluorocarbons",
"halocarbon",
"halocarbons",
"HCFC",
"HCFCs",
"HFC",
"HFCs",
"hydrochlorofluorocarbon",
"hydrochlorofluorocarbons",
"hydrofluorocarbon",
"hydrofluorocarbons",
"NMVOC",
"NMVOCs",
"perfluorocarbon",
"perfluorocarbons",
"aerosol",
"aerosols",
"400ppm",
"climate",
"climatechange",
"globalwarming",
"vulnerability",
"anomaly",
"anomalies",
"spike",
"spikes",
"Flux",
"Oscillation",
"Variability",
"buoy",
"risk",
"albedo",
"albedo-feedback",
"SST",
"reindeer",
"retreat",
"retreating",
"glacier",
"glaciers",
"freeze-up",
"heat",
"heating",
"hot",
"hotter",
"warming",
"wildfire",
"desertification",
"drought",
"permafrost",
"cleantech",
"biofuel",
"biofuels",
"biodiesel",
"ethanol",
"solar",
"decarbonize",
"mitigation",
"mitigate",
"eco-friendly",
"hydropower",
"recycle",
"recycling",
"reforestation",
"afforestation",
"GOES",
"weather@home",
"Otto",
"Cullen",
"Oldenborgh",
"NOAA",
"Oxford",
"ECI",
"Siberia",
"275,000",
"AMO",
"Gaussian",
"aerosols",
"Santa",
"Svalbard",
"NSIDC",
"Longyearbyen",
"WWA",
"AGW",
"IPCC",
"EPA",
"UNFCCC",
"NCA",
"attribution",
"climatecentral",
"climatematters",
"science",
"scientist",
"HadAM3P",
"modulated",
"forecast",
"forecasting",
"probability",
"probabilities",
"unusual",
"rare",
"extreme",
"extremely"
]

CC_PHRASES = [
"anthropogenic climate change",
"carbon emissions",
"carbon dioxide emissions",
"CO2 emissions",
"greenhouse gas",
"greenhouse gases",
"greenhouse gasses",
"greenhouse effect",
"enhanced greenhouse effect",
"heat trapping gas",
"heat trapping gases",
"heat-trapping gas",
"heat-trapping gases",
"coalbed methane",
"fossil fuel",
"fossil fuels",
"power plant",
"power plants",
"coal power plant",
"coal power plants",
"coal fired power plant",
"coal fired power plants",
"coal-fired power plant",
"coal-fired power plants",
"crude oil",
"natural gas",
"hydraulic fracturing",
"carbon dioxide",
"carbon dioxides",
"black carbon",
"carbon footprint",
"carbon pollution",
"carbon sink",
"enteric fermentation",
"fluorinated gas",
"fluorinated gases",
"nitrogen oxide",
"nitrogen oxides",
"nitrous oxide",
"nitrous oxides",
"Keeling Curve",
"400 ppm",
"Mauna Loa",
"particulate matter",
"parts per billion",
"parts per million",
"parts per trillion",
"climate skeptic",
"climate sceptic",
"climate denier",
"climate change",
"climate feedback",
"climate forcing",
"thermal radiation",
"radiative forcing",
"climate sensitivity",
"climate shift",
"climate shifts",
"climate system",
"climate systems",
"climate threshold",
"climate thresholds",
"climate variability",
"climate vulnerability",
"critical threshold",
"critical thresholds",
"global average temperature",
"global warming",
"global warming vulnerability",
"globe has warmed",
"globe is warming",
"globe will be warming",
"tipping point",
"energy balance",
"energy imbalance",
"historical high",
"historical low",
"upward trend",
"above normal",
"large storm",
"large storms",
"jet stream",
"transport heat",
"record low ice extent",
"record high temperatures",
"sea ice",
"sea ice extent",
"sea ice area",
"sea ice dynamics",
"sea ice thin",
"sea ice thinning",
"sea ice retreat",
"sea ice growth",
"sea ice dip",
"unseasonal sea ice decline",
"sea ice melt",
"sea ice melting",
"heat absorbed",
"sea surface temperature",
"sea surface temperatures",
"water temperature",
"water temperatures",
"freezing sea ice",
"re-freezing sea ice",
"Arctic amplification",
"ice free region",
"ice free regions",
"record-low ice coverage",
"freezing point",
"ho, ho, hot!",
"Ho, Ho, Hot!",
"Climate change heats North Pole",
"gaining ice",
"losing ice",
"ice gain",
"ice loss",
"mass of ice",
"vanishing ice",
"ice vanishing",
"melting point",
"glacier melt",
"ice cap melt",
"glacial melt",
"glacier melt",
"melting glaciers",
"ice cap",
"ice cap melting",
"ice caps",
"polar amplification",
"sea ice",
"heat wave",
"extreme heat",
"early winter heat wave",
"above average",
"extreme heat",
"extra warm",
"extra warming",
"warm episode",
"warm episodes",
"extreme warmth",
"extremely warm",
"extreme warm event",
"warming trend",
"fastest-warming",
"temperature anomaly",
"extreme temperature",
"extreme temperatures",
"temperature increase",
"temperature increases",
"large temperature increase",
"large temperature increases",
"largest temperature increase",
"temperature swing",
"temperature swings",
"degrees above normal",
"heat rise and temperatures",
"freak temperature",
"freak temperatures",
"phytoplankton blooming",
"sea level rise",
"sea level rising",
"species extinction",
"invasive species",
"ocean acidification",
"climate refugee",
"climate refugees",
"alternative energy",
"alternative sources of energy",
"alternative power",
"alternative sources of power",
"clean energy",
"clean power",
"renewable energy",
"renewable power",
"renewable sources of energy",
"renewable sources of power",
"advanced biofuel",
"advanced biofuels",
"cellulosic biofuel",
"cellulosic biofuels",
"corn ethanol",
"corn based ethanol",
"corn-based ethanol",
"solar energy",
"solar panel",
"solar panels",
"solar power",
"distributed solar",
"community solar",
"wind energy",
"distributed wind",
"wind power",
"wind turbine",
"wind turbines",
"cap and trade",
"carbon trading",
"carbon tax",
"carbon credit",
"carbon credits",
"carbon offset",
"carbon offsets",
"carbon capture",
"carbon sequestration",
"emission standards",
"emissions trading",
"carbon neutral",
"carbon neutrality",
"zero carbon",
"environmental accounting",
"climate change resilience",
"climate change resilience",
"climate resilience",
"global warming resilience",
"climate adaptation",
"climate change adaptation",
"global warming adaptation",
"climate preparedness",
"climate change preparedness",
"global warming preparedness",
"eco friendly",
"energy efficiency",
"energy efficient",
"Kyoto Protocol",
"Montreal Protocol",
"November-December 2016",
"CMIP5 multi-model ensemble",
"2013 IPCC AR5 report",
"degrees celsius",
"-7 ºC",
"2 ºC",
"3.6 ºF",
"19 ºF",
"15 ºC",
"27 ºF",
"degrees fahrenheit",
"13 ºC",
"23 ºF",
"10 ºC",
"18 ºF",
"Beaufort Sea",
"Dr. Otto",
"Dr Otto",
"Fredi Otto",
"Friederike Otto",
"Heidi Cullen",
"Geert Jan van Oldenborgh",
"Marc Macias-Fauria",
"Andrew King",
"Peter Uhe",
"Sjoukje Philip",
"Sarah Kew",
"David Karoly",
"Jeremy Mathis",
"Zachary Labe",
"Arctic Research Program",
"National Oceanic and Atmospheric Administration",
"Yamal Peninsula",
"North-Western Siberia",
"22 percent out of 275,000",
"decadal North Atlantic variability",
"North Atlantic variability",
"35 degrees Fahrenheit",
"30-35 degrees above normal",
"23 degrees above normal",
"Franz Joseph islands",
"National Snow and Ice Data Center",
"positive feedback",
"Weather Underground",
"40 degrees above normal",
"Climate Central",
"World Weather Attribution",
"Oxford University",
"Environmental Change Institute",
"North Pole Environmental Observatory",
"Intergovernmental Panel on Climate Change",
"Environmental Protection Agency",
"National Climate Assessment",
"event attribution",
"extreme event attribution",
"climate attribution",
"weather attribution",
"extreme weather attribution",
"world weather attribution",
"attribution study",
"climate central",
"climate matters",
"climate science",
"climate scientist",
"climate prediction",
"climate predictions",
"climate projection",
"climate projections",
"climate scenario",
"climate scenarios",
"coupled climate model",
"coupled climate models",
"historical simulation",
"historical simulations",
"event frequency",
"event likelihood",
"weather model",
"weather models",
"historical record",
"historical records",
"satellite imagery",
"satellite image",
"satellite images",
"extremely unlikely",
"extreme event",
"weather system",
"weather systems"
]
