# https://en.wikipedia.org/wiki/Glossary_of_climate_change
CLIMATE_CHANGE_RELATED_WORDS = [
    'adapt',
    'adaptation',
    'all-time',
    'arctic',
    'carbon',
    'catastrophic',
    'celsius',
    'climate',
    # 'change',
    'crisis',
    'cooling',
    'conditions',
    'degree',
    'dioxide',
    'drought',
    'ecosystem',
    'energy',
    'environmental',
    'environment',
    'eco',
    'effect',
    'effort',
    'extreme',
    'footprint',
    'fossil',
    'fuel',
    'gas',
    'glacial',
    'global',
    'greenhouse',
    'green',
    'greenland',
    'heat',
    'historic',
    'historical',
    'history',
    'hottest',
    'high',
    'ice',
    'life-threatening',
    'megadrought',
    'mega-drought',
    'mega-fire',
    'mega-fires',
    'meteorologist',
    'meteorology',
    'methane',
    'mitigation',
    'natural',
    'nitrous',
    'ozone',
    'offset',
    'oxide',
    'planet',
    'policies',
    'policy',
    'pollution',
    'record',
    'record-breaking',
    'record-setting',
    'report',
    'reversable',
    'reverse',
    'renewable',
    'resource',
    'rise',
    'rising',
    'science',
    'scientist',
    'scientists',
    'sea ice',
    'sea',
    'sea-level',
    'severe',
    'shrinkage',
    'solar',
    'temperature',
    'temperatures',
    'unprecedented',
    'warm',
    'warmest',
    'warmed',
    'warming',
    #'weather',
    'wildfire',
    'worsening',
    'worse',
    'worst'
]
CLIMATE_CHANGE_RELATED_WORDS.sort()

CLIMATE_CHANGE_RELATED_PHRASES = [
    'arctic shrinkage',
    'carbon dioxide',
    'carbon footprint',
    'carbon offset',
    'carbon tax',
    'climate change',
    'climate crisis',
    'climate justice',
    'climate policy',
    'dangerous heat waves',
    'extreme drought',
    'extreme weather event',
    'weather event',
    'weather events',
    'fossil fuel',
    'global climate',
    'global cooling',
    'global warming',
    'global warming controversy',
    'global warming denial',
    'greenhouse debt',
    'greenhouse effect',
    'greenhouse gas',
    'greenland ice sheet',
    'historical temperature record',
    'historic levels',
    'historic level',
    'heat wave',
    'ice sheet',
    'natural gas',
    'nitrous oxide',
    'record setting'
    'record breaking',
    'record breaking',
    'renewable resource',
    'sea level',
    'severe weather',
    'weather extremes',
    'worsening conditions'
]
CLIMATE_CHANGE_RELATED_PHRASES.sort()

if __name__ == '__main__':
    main()
